version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    #image: go-app-image
    container_name: go-app
    env_file:
      - .env
    environment:
      GREENLIGHT_DB_DSN: ${GREENLIGHT_DB_DSN}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data: